backend/models/EventsForm.php
<?php
/**
 * Created by PhpStorm.
 * User: filip
 * Date: 12.07.2018
 * Time: 17:40
 */

namespace backend\models;


use yii\base\Model;

class EventsForm extends Model
{
    public $name;
    public $img;
    public $fullLocation;
    public $city;
    public $place;
    public $lat;
    public $lng;
    public $start;
    public $end;
    public $info;

    public function rules()
    {
        return [
            [['start', 'end','info','fullLocation', 'name'], 'required', 'on'=>'create'],
            [['start', 'end','city,','place','lat','lng','info','fullLocation', 'name'],'string'],
            [['img'], 'file', 'extensions'=>'jpg, gif, png', 'maxFiles' => 1, 'maxSize' => 1024 * 1024 * 1],

            [['name'], 'string', 'max'=>100],
            [['info'], 'string', 'max'=>500]
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Nazwa wydarzenia',
            'start' => 'Początek',
            'end' => 'Zakończenie',
            'city' => 'Miasto',
            'place' => 'Miejsce',
            'info' => 'Opis',
            'fullLocation' => 'Lokalizacja',
            'img'=>'Zdjecia'
        ];
    }




}

backend/controllers/TalksController.php
<?php
/**
 * Created by PhpStorm.
 * User: filip
 * Date: 12.07.2018
 * Time: 17:41
 */

namespace backend\controllers;


use backend\api\Api;
use backend\models\TalksForm;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use backend\controllers\CookiesController;

class TalksController extends Controller
{
    public function actionCreate($eventId){
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $validation = new CookiesController();
        $validation->CookiesValidation();
        $cookie = Yii::$app->request->cookies;
        $sid = $cookie->getValue('sid');

        $model = new TalksForm();

        $api = new Api(Yii::$app->params['apiDomain']);
        $curl = $api->get('event/'.$eventId,[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $arr = json_decode($curl->response, true);
        date_default_timezone_set('Europe/Warsaw');

        $eventStartDateConverted = Date('Y-m-d H:i',$arr['date']['start']);
        $eventEndDateConverted = Date('Y-m-d H:i',$arr['date']['end']);

        $eventStartDate = $eventStartDateConverted;
        $eventEndDate = $eventEndDateConverted;

        if ($model->load(Yii::$app->request->post())) {


            $current_date = strtotime(date('Y-m-d H:i'));
            if(strtotime($model->start) <= $current_date || strtotime($model->end <= $current_date)){
                Yii::$app->getSession()->setFlash('error', 'Wydarzenie już się skończyło');
                return $this->render('create', [
                    'model' => $model,
                    'eventStartDate' => $eventStartDate,
                    'eventEndDate' => $eventEndDate
                ]);
            }else {


                $curl = $api->postTalk($model->title, $model->start, $model->end, $model->speakers, $eventId, $sid);


                if ($curl->responseCode == 201) {
                    Yii::$app->getSession()->setFlash('success', 'Dodano prelekcje');
                    return $this->redirect('../events/view-event?id='. $eventId);

                }elseif($curl->responseCode == 400){
                    Yii::$app->getSession()->setFlash('error', 'Złe dane');
                }else{
                    Yii::$app->getSession()->setFlash('error', 'Błąd serwera');
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'eventStartDate' => $eventStartDate,
            'eventEndDate' => $eventEndDate
        ]);
    }

    /**
     * @param $id
     * @param $sid
     * @param $eventId
     * @return \yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionDeleteTalks($id, $sid, $eventId)
    {

        $delete = new Api(Yii::$app->params['apiDomain']);
        $delete->delete('talk/' . $id, $sid);
        Yii::$app->getSession()->setFlash('success', 'Usunięto prelekcje');
        return $this->redirect('../events/view-event?id='. $eventId);

    }

    /**
     * @param $id
     * @param $eventId
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     * @internal param $sid
     */
    public function actionUpdateTalks($id, $eventId)
    {

        $model = new TalksForm();
        //validation
        $validation = new CookiesController();
        $validation->CookiesValidation();
        $cookie = Yii::$app->request->cookies;
        $sid = $cookie->getValue('sid');

        $api = new Api(Yii::$app->params['apiDomain']);
        $curl = $api->get('talk/'.$id,[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $talkData = json_decode($curl->response, true);
        date_default_timezone_set('Europe/Warsaw');


        $date = $talkData['date'];
        $speakers = $talkData['speakers'];
        $start = $date['start'];
        $end = $date['end'];
        $model->start = date("Y-m-d H:i:s",$start);
        $model->end = date("Y-m-d H:i:s",$end);
        $model->title = $talkData['title'];

        $curl_event = $api->get('event/'.$eventId,[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $eventData = json_decode($curl_event->response, true);

        $eventStartDateConverted = Date('Y-m-d H:i',$eventData['date']['start']);
        $eventEndDateConverted = Date('Y-m-d H:i',$eventData['date']['end']);

        $eventStartDate = $eventStartDateConverted;
        $eventEndDate = $eventEndDateConverted;

        $model->speakers = ArrayHelper::getColumn($speakers, '_id');

        if ($model->load(Yii::$app->request->post())) {

            $start = strtotime($model->start);
            $end = strtotime($model->end);
            $array = [
                'title' => $model->title,
                'date' =>[
                    'start' => $start,
                    'end' => $end,
                ],
                'speakers' => $model->speakers
            ];



            $curl = $api->patch('talk/'.$id, $array, $sid);
            if($curl->responseCode == 200){
                Yii::$app->getSession()->setFlash('success', 'Zaktualizowano prelekcje');
                return $this->redirect('../events/view-event?id='. $eventId);
            }elseif($curl->responseCode == 400){
                Yii::$app->getSession()->setFlash('error', 'Złe dane');
            }else{
                Yii::$app->getSession()->setFlash('error', 'Błąd serwera');
            }
        }
        return $this->render('update', [
            'model' => $model,
            'eventStartDate' => $eventStartDate,
            'eventEndDate' => $eventEndDate
        ]);
    }
    public function actionViewTalks($id){

        $model = new TalksForm();
        //validation
        $validation = new CookiesController();
        $validation->CookiesValidation();
        $cookie = Yii::$app->request->cookies;
        $sid = $cookie->getValue('sid');

        $api = new Api(Yii::$app->params['apiDomain']);
        $curl = $api->get('talk/'.$id,[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $arr = json_decode($curl->response, true);
        date_default_timezone_set('Europe/Warsaw');

        $date = $arr['date'];
        $speakers = $arr['speakers'];

        $model->start = date('Y-m-d H:i:s',$date['start']);
        $model->end = date('Y-m-d H:i:s',$date['end']);
        $model->title = $arr['title'];

        $speakers_size = count($speakers);
        for($i = 0;$i<$speakers_size;$i++) {
            $speaker_access = $speakers[$i];
                $speaker_id = $speaker_access['_id'];
            $get_speaker = $api->get('user/' . $speaker_id, [
                "Content-Type: application/json; charset=UTF-8",
                "Cookie: $sid",]);

            $speaker_json = $get_speaker->response;
            $ar = json_decode($speaker_json);
            $speaker_array = json_decode(json_encode($ar), true);
            $model->speakers = $speaker_array['name'];
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

}

backend/views/events/create.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \backend\models\EventsForm*/

use kartik\datetime\DateTimePicker;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\file\FileInput;

$this->title = 'Dodawanie wydarzenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= Html::encode($this->title) ?></h1>
<div class="site-login">
    <div class="row">
        <div class="col-lg-6">
            <?php $form = ActiveForm::begin(['id' => 'Signup-form', 'options' => ['enctype' => 'multipart/form-data']]); ?>
            

                <div class="col-12"><?= $form->field($model, 'name') ?></div>
                <div class="col-12"><?= $form->field($model, 'info')->textarea(['rows' => '6']) ?></div>
                <div class="col-12">
                    <?= $form->field($model, 'start')->widget(DateTimePicker::class, [
                        'type' => DateTimePicker::TYPE_INPUT,
                    'options' => ['placeholder' => 'Początek wydarzenia','readonly' => true],
                    'pluginOptions' => ['autoclose' => true,  'startDate' => date("Y-m-d H:i")]
                    ]); ?>
                </div>
                <div class="col-12">
                    <?= $form->field($model, 'end')->widget(DateTimePicker::class, [
                    'type' => DateTimePicker::TYPE_INPUT,
                    'options' => ['placeholder' => 'Koniec wydarzenia','readonly' => true],
                    'pluginOptions' => ['autoclose' => true, 'startDate' => date("Y-m-d H:i")]
                    ]); ?>
                </div>
        <?php
        echo '<label class="control-label">Logo wydarzenia</label>';
        echo FileInput::widget([
            'name' => 'img',
            'options' =>[
                'allowedFileTypes' =>'image',
                'allowedFileExtensions' => 'jpg, gif, png',
                'maxFileSize' => '1000'
            ],
            'pluginOptions'=>[
                  'showCancel'=> false,
                  'showUpload' =>false
            ]
        ]);
        ?>
    </div>



            <div class="col-lg-6">
                <div class="google-maps">
                    <?= $form->field($model, 'fullLocation')->widget(\kalyabin\maplocation\SelectMapLocationWidget::class, [
                        'attributeLatitude' => 'lat',
                        'attributeLongitude' => 'lng',
                        'googleMapApiKey' => 'AIzaSyDNQA-S5FN7HNz9Q7RPL5zSZD3yj8vwebE',
                        'draggable' => true,
                        'class' => 'google-maps' ]);
                    ?>
                </div>
                <div class="form-btn">
                    <?= Html::submitButton('Dodaj', ['class' => 'btn btn-info add-event-btn', 'name' => 'create-talk-button']) ?>
                </div>
            </div>
        
            <?php ActiveForm::end(); ?>

            <div class="popup sadPrompt">
            <?php if (Yii::$app->session->hasFlash('error')): ?>
                    <div class="alert alert-error alert-dismissable">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"><i class="icon-cancel"></i></button>
                        <h4><i class="icon-icon-alert"></i>Błąd</h4>
                        <?= Yii::$app->session->getFlash('error') ?>
                    </div>
                    <?php endif; ?>
            </div>
            
            
        </div>   
    </div>
</div>






                

backend/views/events/index.php
<?php

use backend\api\Api;
use backend\controllers\CookiesController;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model \backend\models\EventsForm*/

$this->title = 'Wydarzenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    table, th, td {
        border-collapse: collapse;
        overflow-x:auto ;
    }
    table{
        margin-top:30px;
    }
    th, td {
        font-weight:600;
        padding: 5px;
        margin: 10px;
        text-align: center;
        color:var(--dark-c);
        border-bottom: 3px solid var(--dark-c);
        border-top: 1px solid var(--dark-c);
        border-left: 1px solid var(--dark-c);
        border-right: 1px solid var(--dark-c);
        background:white;
    }
    .add-btn{
        margin-top:20px;
        width:100px;
    }
</style>
</head>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>

     <?= Html::a('Dodaj', ['create'], ['class' => 'btn btn-info add-event-btn']) ?>
     
    <div class="tabelka">
    <?php
            $api = new Api(Yii::$app->params['apiDomain']);
            $cookie = Yii::$app->request->cookies;
            $sid = $cookie->getValue('sid');
            $userData = $cookie->getValue('user');

    if($sid == null){
        //validation
        $validation = new CookiesController();
        $validation->CookiesValidation();
    }else {

        if($userData['type'] == 3){
            $curl = $api->get('event', [
                "Content-Type: application/json; charset=UTF-8",
                "Cookie: $sid",]);
        }else{
            $curl = $api->get('event/user/'. $userData['userId'], [
                "Content-Type: application/json; charset=UTF-8",
                "Cookie: $sid",]);
        }
        $event = json_decode($curl->response, true);
        if($event == null){
            $size = 0;
        }else{
            $size = count($event);
        }

        echo '<table style="width:100%;">
    <tr>
    <th>Nazwa</th>
    <th>Miasto</th> 
    <th>Miejsce</th>
    <th>Początek</th> 
    <th>Koniec</th>
    <th>Status</th>
    <th>Średnia ocen</th>
    <th>Ilość głosów</th>
    <th style="width:150px;min-width:150px;">Operacje</th>
  </tr>';
        for ($i = 0; $i < $size - 1; $i++) {
            $a = $event[$i];
            $location = $a['location'];
            $date = $a['date'];
            $feedBack = $a['feedback'];

            if($a['status'] == 'archive'){
                $status = 'Zakończony';
            }elseif ($a['status'] == 'future'){
                $status = 'Przyszły';
            }elseif ($a['status'] == 'actual'){
                $status = 'W trakcie';
            }else{
                $status = 'BŁĄD!';
            }
            date_default_timezone_set('Europe/Warsaw');
            $dateStart = date('Y-m-d H:i:s', $date['start']);
            $dateEnd = date('Y-m-d H:i:s', $date['end']);

            echo '<tr>
            <td>' . $a['name'] . '</td>
            <td>' . $location['city'] . '</td>
            <td>' . $location['place'] . '</td> 
            <td>' . $dateStart . '</td>
            <td>' . $dateEnd . '</td> 
            <td>' . $status . '</td>
            <td>' . round($feedBack['avg'], 2) . '/5' . '</td> 
            <td>' . $feedBack['count'] . '</td>
            <td>' .Html::a('<i class="icon-trash-empty col-6"></i>', \yii\helpers\Url::to(['delete-event', 'id' => $a['_id'], 'sid' => $sid]), ['class' => 'btn   sadPrompt float justTwo',
                    'data' => [
                        'confirm' => 'Czy napewno chcesz skasować to wydarzenie?',
                        'method' => 'post',]]) .'
                '.Html::a('<i class="icon-search col-6"></i>', \yii\helpers\Url::to(['view-event', 'id' => $a['_id']]), ['class' => 'btn  happyPrompt float justTwo']);
            $current_date = strtotime(date('Y-m-d H:i'));
            if($date['start'] >= $current_date || $date['end'] >= $current_date){
                echo Html::a('<i class="icon-pencil col-4"></i>', \yii\helpers\Url::to(['update-event', 'id' => $a['_id']]), ['class' => 'btn blasePrompt float']) . '
                </td></tr>';
            }else{
                echo '</td></tr>';
            }


        }
        echo '</table>';

    }?>
    </div>
</div>

<div class="popup happyPrompt">
            <?php if (Yii::$app->session->hasFlash('success')): ?>
                    <div class="alert alert-error alert-dismissable">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"><i class="icon-cancel"></i></button>
                        <h4><i class="icon-icon-alert"></i>Sukces!</h4>
                        <?= Yii::$app->session->getFlash('success') ?>
                    </div>
                    <?php endif; ?>
            </div>

backend/views/events/view.php
<?php
/**
 * Created by PhpStorm.
 * User: rst_user_1
 * Date: 17.07.2018
 * Time: 08:25
 */

use yii\bootstrap\ActiveForm;
use backend\api\Api;
use yii\bootstrap\Modal;
use yii\helpers\Html;

$this->title = 'Podgląd wydarzenia';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    table, th, td {
        border-collapse: collapse;
        overflow-x:auto ;
    }
    table{
        margin-top:30px;
    }
    th, td {
        font-weight:600;
        padding: 5px;
        margin: 10px;
        text-align: center;
        color:var(--dark-c);
        border-bottom: 3px solid var(--dark-c);
        border-top: 1px solid var(--dark-c);
        border-left: 1px solid var(--dark-c);
        border-right: 1px solid var(--dark-c);
        background:white;
    }
    .add-btn{
        margin-top:20px;
        width:100px;
    }
    .rate-event {
    background: -webkit-linear-gradient(180deg, #34c868, #11856e);
    color: white;
    cursor: pointer;
    padding: 10px;
    width: 100%;
    margin-top:28px;
    border-radius: 5px 5px 0px 0px;
    border: none;
    text-align: center;
    outline: none;
    font-size: 17px;
    transition: 0.4s;
}

.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}
.dropbtn:hover{
    box-shadow: 0px 2px 23px 2px rgba(17, 133, 110,.3);
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: white;
    min-width: 230px;
    overflow: auto;
    border-left: 5px solid #11856e;
    border-right: 5px solid #34c868;
    border-bottom: 5px solid #11856e;
    z-index: 1;
    padding: 0px;
    max-height: 300px;
    overflow-y: auto;
}
.showRate{display: block;}

.event-rate{
    border-bottom: 2px solid  #11856e;
    margin:0px;
    padding:4px;
    overflow:scroll;
    max-width:100%;
    max-height:100px;
    position: relative;
    overflow-y:hidden;
    max-height:50%;
    min-height:80px;
}
h1{
    margin:0px;
}
.rate, .comment, .event-rate h1{
    float:left;
}
.rate{
    height:100% !important;
    padding: 10px;

}
.non-rate{
    text-align:center;
}
.non-rate h1{
    font-size:18px!important;
    margin-top:10px;
    text-align:center;
    margin-left: calc(50% - 165px);
}
h5{
    font-size:16px!important;
    text-align:justify!important;
    padding:5px;

}
h5:after{
    content: "";
    clear:both;
}
.view-event-img{
    max-width:100%;
    max-height: 300px;
    margin: 30px auto 0px auto;
    display:block;
}
.rate{
    float:left;
    position: absolute;
    top:0px;
    left:0px;
}
.comment{
    float:left;
    padding : 10px;
    text-align:justify;
    overflow-x:scroll;
    margin-left:65px;
}
.rate-date{
    position: absolute;
    bottom:-5px;
    right:10px;
    float:left;
}
.rate-date:after{
    content:"";
    clear:both;
}
.non-rate h1{
    text-align:center!important;
    float:none;
}


</style>
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-lg-6">
            <?php $form = ActiveForm::begin(['id' => 'view-form']); ?>

                <?= $form->field($model, 'name')->textInput(['readonly' => true]) ?>
                <?= $form->field($model, 'info')->textarea(['rows' => '6', 'readonly' => true])?>
                <?= $form->field($model, 'start')->textInput(['readonly' => true]) ?>
                <?= $form->field($model, 'end')->textInput(['readonly' => true]) ?>
                <?=
                $form->field($model, 'fullLocation')->widget(\kalyabin\maplocation\SelectMapLocationWidget::class, [
                    'attributeLatitude' => 'lat',
                    'attributeLongitude' => 'lng',
                    'googleMapApiKey' => 'AIzaSyDNQA-S5FN7HNz9Q7RPL5zSZD3yj8vwebE',
                    'draggable' => false,
                ])->textInput(['readonly' => true]); ?>

            <?php ActiveForm::end(); ?>
        </div>
        <?php
        $api = new Api(Yii::$app->params['apiDomain']);
        $cookie = Yii::$app->request->cookies;
        $sid = $cookie->getValue('sid');
        $curl = $api->get('event/'. $_GET['id'],[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);

        $rating = json_decode($curl->response,true);
        ?>

        

        <div class="col-lg-6">
        <img class="view-event-img" src='data:image/png;base64, <?= $rating["img"] ?>'/>

            <div class="dropdown">
                <button onclick="myFunction()" class="dropbtn col-12 rate-event"><h3>Oceny wydarzenia</h3></button>
                <div id="myDropdown" class="dropdown-content col-12">

                    <?php
                $rating = $rating['feedback'];
                $rating_size = count($rating);
                if($rating_size == 1){
                   
                    echo '<div class="event-rate non-rate just-rate">
                                <h1>Wydarzenie nie zostało jeszcze ocenione</h1>
                          </div>';
                }

                for($i = 0; $i < $rating_size-1; $i++){
                    $rating_one = $rating[$i];
                    $date = date('d-m-Y H:i',$rating_one['date']);
                    if($rating_one['content'] != null){
                        echo '<div class="event-rate">
                                    <div  class="rate">
                                        <h1>'. $rating_one["rating"] .'/5</h1>
                                    </div>
                                    <div class="comment">
                                        '. $rating_one['content'] .'
                                    </div>
                                    <div class="rate-date">
                                        <h6 class="date-rate" >'. $date .'</h6>
                                    </div>
                                </div>';
                    }else{
                        echo '<div class="event-rate">
                                    <div  class="rate">
                                        <h1>'. $rating_one["rating"] .'/5</h1>
                                    </div>
                                    <div class="rate-date">
                                        <h6 class="date-rate" >'. $date .'</h6>
                                    </div>
                                </div>';
                    }
                }
                ?>

            </div>
        </div>

        <script>
            function myFunction() {
            document.getElementById("myDropdown").classList.toggle("showRate");
            }
        </script>


        <?php
        $api = new Api(Yii::$app->params['apiDomain']);
        $cookie = Yii::$app->request->cookies;
        $sid = $cookie->getValue('sid');
        $talksDate = $api->get('talk/event/'.$_GET['id'],[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $talk = json_decode($talksDate->response, true);
        $size = count($talk);


        $eventDate = $api->get('event/'. $_GET['id'],[
            "Content-Type: application/json; charset=UTF-8",
            "Cookie: $sid",]);
        $eventDate = json_decode($eventDate->response,true);

        $current_date = strtotime(date('Y-m-d H:i'));
        if($eventDate['date']['start'] >= $current_date || $eventDate['date']['start'] >= $current_date){
            echo Html::a('Dodaj', \yii\helpers\Url::to(['/talks/create', 'eventId'=>$_GET['id']]), ['class'=>'btn add-event-btn btn-info']);
        }


        echo   '<div class="tabelka">';
        echo '<table style="width:100%">
    <tr>
    <th>Tytuł prelekcji</th>
    <th>Prelegenci</th> 
    <th>Poczatek prelekcji</th> 
    <th>Koniec prelekcji</th>
    <th style="width:150px;min-width:150px;">Operacje</th>
  </tr>';
        for($i = 0;$i<$size;$i++) {
            $a = $talk[$i];
            $date = $a['date'];
            $speaker = $a['speakers'];
            $speaker_size = count($speaker);

            date_default_timezone_set('Europe/Warsaw');

            $date['start'];
            $dateStart = date('Y-m-d H:i:s',$date['start']);
            $dateEnd = date('Y-m-d H:i:s',$date['end']);

            for($c = 0;$c < $speaker_size;$c++){

                $get_speaker = $api->get('user/' . $speaker[$c], [
                    "Content-Type: application/json; charset=UTF-8",
                    "Cookie: $sid",]);


                $speaker_json = $get_speaker->response;
                $ar = json_decode($speaker_json);
                $speaker_array = json_decode(json_encode($ar), true);
                $speaker_name = $speaker_array['name'];
            }



            echo '<tr><td>' . $a['title'] . '</td><td> ';

            for($c = 0;$c < $speaker_size;$c++){

                $get_speaker = $api->get('user/' . $speaker[$c], [
                    "Content-Type: application/json; charset=UTF-8",
                    "Cookie: $sid",]);


                $speaker_json = $get_speaker->response;
                $ar = json_decode($speaker_json);
                $speaker_array = json_decode(json_encode($ar), true);
                $speaker_name = $speaker_array['name'];
                echo $speaker_array['name']."</br>";
            }


            echo '
                </td> 
                 <td>' . $dateStart . '</td>
                 <td>' . $dateEnd . '</td>
                <td>
                '. Html::a('<i class="icon-trash-empty col-4"></i>', \yii\helpers\Url::to(['../talks/delete-talks', 'id' => $a['_id'], 'sid' => $sid, 'eventId' => $_GET['id']]), [
                    'class' => 'btn   sadPrompt float',
                    'data' => [
                        'confirm' => 'Czy napewno chcesz skasować tę prelekcję?',
                        'method' => 'post',]]) .'
                '.Html::a('<i class="icon-search col-4"></i>', \yii\helpers\Url::to(['../talks/view-talks', 'id' => $a['_id']]), ['class' => 'btn  happyPrompt float']);
            if($eventDate['date']['start'] >= $current_date || $eventDate['date']['start'] >= $current_date) {
                echo Html::a('<i class="icon-pencil col-4"></i>', \yii\helpers\Url::to(['../talks/update-talks', 'id' => $a['_id'], 'eventId' => $_GET['id']]), ['class' => 'btn blasePrompt float']) . '
             </td></tr>';
            }else{
                echo '</td></tr>';
            }

        }
        echo '</table>';
        echo '</div>';
        ?>


        </div>
    </div>

    <div class="popup happyPrompt">
<?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-error alert-dismissable">
        <button aria-hidden="true" data-dismiss="alert" class="close" type="button"><i class="icon-cancel"></i></button>
        <h4><i class="icon-icon-alert"></i>Sukces!</h4>
        <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>
    </div>